In [13]:
import hydrobr
import pandas as pd

ModuleNotFoundError: No module named 'folium'

# Filtros para fazer download

In [5]:
# Listando todas as estações do hydroBR
lista_estacoes = hydrobr.get_data.ANA.list_prec_stations()
lista_estacoes.head()

,Name,Code,Type,SubBasin,City,State,Responsible,Latitude,Longitude,StartDate,EndDate,NYD,MD,N_YWOMD,YWMD
0,SALINÓPOLIS,00047000,2,32,SALINÓPOLIS,PARÁ,INMET,-0.6500,-47.5500,1958/01/01,1964/12/31,7,25.0,0,100.0
1,SALINÓPOLIS,00047002,2,32,SALINÓPOLIS,PARÁ,ANA,-0.6231,-47.3536,1977/12/09,2019/08/31,43,3.5,35,18.6
2,CURUÇA,00047003,2,32,CURUÇA,PARÁ,ANA,-0.7375,-47.8536,1981/07/01,2019/07/31,39,2.4,29,25.6
3,PRIMAVERA,00047004,2,32,PRIMAVERA,PARÁ,ANA,-0.9294,-47.0994,1982/02/18,2019/08/31,38,0.0,35,7.9
4,MARUDA,00047005,2,32,MARAPANIM,PARÁ,ANA,-0.6336,-47.6583,1989/08/21,2019/07/31,31,5.0,20,35.5

In [6]:
# Filtrando para o Estado e a Empresa responsável
lista_estacoes_state = lista_estacoes[lista_estacoes.State=='RIO DE JANEIRO']
lista_estacoes_state_ana = lista_estacoes_state[lista_estacoes_state.Responsible=='ANA']
lista_estacoes_state_ana

,Name,Code,Type,SubBasin,City,State,Responsible,Latitude,Longitude,StartDate,EndDate,NYD,MD,N_YWOMD,YWMD
6443,VARRE - SAI,02041046,2,57,NATIVIDADE,RIO DE JANEIRO,ANA,-20.9314,-41.8678,1967/06/24,2019/09/30,53,3.0,28,47.2
6453,SANTA RITA DO PRATA,02041141,2,57,VARRE-SAI,RIO DE JANEIRO,ANA,-20.8589,-41.7419,2017/07/24,2019/10/31,3,0.0,1,66.7
6477,PORCIUNCULA,02042027,2,58,PORCIÚNCULA,RIO DE JANEIRO,ANA,-20.9692,-42.0517,1939/01/01,2019/10/31,81,0.9,68,16.0
6950,SÃO FRANCISCO PAULA - CACIMBAS,02141001,2,57,SÃO JOÃO DA BARRA,RIO DE JANEIRO,ANA,-21.4828,-41.1033,1972/01/01,2019/08/31,48,4.4,31,35.4
6951,CAMPOS - PONTE MUNICIPAL,02141002,2,58,CAMPO DOS GOYTACAZE,RIO DE JANEIRO,ANA,-21.7533,-41.3003,1945/04/01,2019/06/30,75,40.8,33,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9023,PATRIMÔNIO,02344006,2,59,PARATI,RIO DE JANEIRO,ANA,-23.3172,-44.7217,1967/09/01,2019/10/31,53,1.6,30,43.4
9024,PARATI,02344007,2,59,PARATI,RIO DE JANEIRO,ANA,-23.2242,-44.7642,1962/08/24,2019/10/31,58,1.1,40,31.0
9025,SÃO ROQUE,02344008,2,59,PARATI,RIO DE JANEIRO,ANA,-23.0722,-44.6981,1967/09/01,2019/09/30,53,0.2,41,22.6
9030,VILA MAMBUCABA,02344016,2,59,ANGRA DOS REIS,RIO DE JANEIRO,ANA,-23.0258,-44.5181,1982/02/09,2019/10/31,38,0.5,29,23.7
9033,VILA PEREQUE,02344019,2,59,ANGRA DOS REIS,RIO DE JANEIRO,ANA,-23.0047,-44.5364,1994/12/10,2019/09/30,26,0.2,21,19.2

## Mapa com marcação das estações

In [12]:
# Para criar o mapa utilizando folium

mapa = folium.Map(location=[-29.2323,-51.3232],
                  zoom_start=6,
                  min_zoom=6,
                  tiles='Stamen Terrain')

# Para adicionar as marcações de acordo com a latitude e longitude do DataFrame

nome = lista_estacoes_state_ana['Name']
codigo = lista_estacoes_state_ana['Code']
latitude = lista_estacoes_state_ana['Latitude']
longitude = lista_estacoes_state_ana['Longitude']

for name,code,lat,lng in zip(nome,codigo,latitude,longitude):
    folium.Marker([lat,lng], tooltip = {'Estação': name, 'Código': code}).add_to(mapa)
mapa

NameError: name 'folium' is not defined

In [14]:
codigos_estaçoes = lista_estacoes_state_ana.Code.to_list()[0:]
codigos_estaçoes

['02041046',
 '02041141',
 '02042027',
 '02141001',
 '02141002',
 '02141003',
 '02141004',
 '02141005',
 '02141006',
 '02141007',
 '02141008',
 '02141009',
 '02141011',
 '02141012',
 '02142014',
 '02142015',
 '02142016',
 '02142017',
 '02142019',
 '02142022',
 '02142058',
 '02142067',
 '02142078',
 '02241001',
 '02241002',
 '02241003',
 '02241004',
 '02242001',
 '02242002',
 '02242003',
 '02242004',
 '02242005',
 '02242006',
 '02242007',
 '02242008',
 '02242009',
 '02242010',
 '02242011',
 '02242012',
 '02242013',
 '02242014',
 '02242015',
 '02242016',
 '02242017',
 '02242018',
 '02242019',
 '02242020',
 '02242021',
 '02242022',
 '02242023',
 '02242024',
 '02242025',
 '02242026',
 '02242027',
 '02242028',
 '02242029',
 '02242031',
 '02242032',
 '02242033',
 '02242034',
 '02243001',
 '02243002',
 '02243003',
 '02243004',
 '02243005',
 '02243006',
 '02243007',
 '02243008',
 '02243009',
 '02243010',
 '02243011',
 '02243012',
 '02243013',
 '02243014',
 '02243015',
 '02243016',
 '02243017',
 '02243018',
 '02243020',
 '02243025',
 '02243159',
 '02243203',
 '02243204',
 '02243229',
 '02243250',
 '02243268',
 '02244028',
 '02244030',
 '02244032',
 '02244033',
 '02244034',
 '02244037',
 '02244038',
 '02244039',
 '02244040',
 '02244041',
 '02244043',
 '02244044',
 '02244045',
 '02244046',
 '02244047',
 '02244049',
 '02244051',
 '02244078',
 '02244079',
 '02244148',
 '02244149',
 '02344006',
 '02344007',
 '02344008',
 '02344016',
 '02344019']

In [15]:
dados_estacoes = hydrobr.get_data.ANA.prec_data(codigos_estaçoes)

100%|██████████| 112/112 [28:39<00:00, 15.35s/it]

In [18]:
from plotly.offline import plot

gantt_fig = hydrobr.Plot.gantt(dados_estacoes) #Get the Gantt Fig

#Updating the layout
gantt_fig.update_layout(
    autosize=True,
    width=5000,
    height=1000,
    xaxis_title = 'Ano',
    yaxis_title = 'Código Estação',
    font=dict(family="Courier New, monospace", size=9))

#To plot and save the gantt plot as html
plot(gantt_fig,filename='gantt' + '.html')

Station 02142015 has no months with significant data
Station 02244051 has no months with significant data

'gantt.html'